//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMDObjectRepository.Forecast {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Forecast {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Forecast() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMDObjectRepository.Forecast.Forecast", typeof(Forecast).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lblHistoricalForecast.
        /// </summary>
        public static string RadioButtonDataSetHistoricalForecastID {
            get {
                return ResourceManager.GetString("RadioButtonDataSetHistoricalForecastID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lblHistorical.
        /// </summary>
        public static string RadioButtonDataSetHistoricalID {
            get {
                return ResourceManager.GetString("RadioButtonDataSetHistoricalID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lblDevTypeAdditionAlteration.
        /// </summary>
        public static string RadioButtonDevTypeAdditionAlterationID {
            get {
                return ResourceManager.GetString("RadioButtonDevTypeAdditionAlterationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lblDevTypeAddition.
        /// </summary>
        public static string RadioButtonDevTypeAdditionID {
            get {
                return ResourceManager.GetString("RadioButtonDevTypeAdditionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lblDevTypeAll.
        /// </summary>
        public static string RadioButtonDevTypeAllID {
            get {
                return ResourceManager.GetString("RadioButtonDevTypeAllID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lblDevTypeAlteration.
        /// </summary>
        public static string RadioButtonDevTypeAlterationID {
            get {
                return ResourceManager.GetString("RadioButtonDevTypeAlterationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lblDevTypeNewAddition.
        /// </summary>
        public static string RadioButtonDevTypeNewAdditionID {
            get {
                return ResourceManager.GetString("RadioButtonDevTypeNewAdditionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lblDevTypeNew.
        /// </summary>
        public static string RadioButtonDevTypeNewID {
            get {
                return ResourceManager.GetString("RadioButtonDevTypeNewID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lblDevTypeRen.
        /// </summary>
        public static string RadioButtonDevTypeRenovationID {
            get {
                return ResourceManager.GetString("RadioButtonDevTypeRenovationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lblMeasProjects.
        /// </summary>
        public static string RadioButtonMeasurementProjectsID {
            get {
                return ResourceManager.GetString("RadioButtonMeasurementProjectsID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lblMeasSQFT.
        /// </summary>
        public static string RadioButtonMeasurementSqFtID {
            get {
                return ResourceManager.GetString("RadioButtonMeasurementSqFtID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lblMeasValue.
        /// </summary>
        public static string RadioButtonMeasurementValueID {
            get {
                return ResourceManager.GetString("RadioButtonMeasurementValueID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rbDataHistoricalForecast.
        /// </summary>
        public static string Span_RadioButtonDataSetHistoricalForecastID {
            get {
                return ResourceManager.GetString("Span_RadioButtonDataSetHistoricalForecastID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rbDataHistorical.
        /// </summary>
        public static string Span_RadioButtonDataSetHistoricalID {
            get {
                return ResourceManager.GetString("Span_RadioButtonDataSetHistoricalID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rbDevelopmentTypeAdditionAlteration.
        /// </summary>
        public static string Span_RadioButtonDevTypeAdditionAlterationID {
            get {
                return ResourceManager.GetString("Span_RadioButtonDevTypeAdditionAlterationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rbDevelopmentTypeAddition.
        /// </summary>
        public static string Span_RadioButtonDevTypeAdditionID {
            get {
                return ResourceManager.GetString("Span_RadioButtonDevTypeAdditionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rbDevelopmentTypeAll.
        /// </summary>
        public static string Span_RadioButtonDevTypeAllID {
            get {
                return ResourceManager.GetString("Span_RadioButtonDevTypeAllID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rbDevelopmentTypeAlteration.
        /// </summary>
        public static string Span_RadioButtonDevTypeAlterationID {
            get {
                return ResourceManager.GetString("Span_RadioButtonDevTypeAlterationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rbDevelopmentTypeNewAddition.
        /// </summary>
        public static string Span_RadioButtonDevTypeNewAdditionID {
            get {
                return ResourceManager.GetString("Span_RadioButtonDevTypeNewAdditionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rbDevelopmentTypeNew.
        /// </summary>
        public static string Span_RadioButtonDevTypeNewID {
            get {
                return ResourceManager.GetString("Span_RadioButtonDevTypeNewID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rbDevelopmentTypeRen.
        /// </summary>
        public static string Span_RadioButtonDevTypeRenovationID {
            get {
                return ResourceManager.GetString("Span_RadioButtonDevTypeRenovationID", resourceCulture);
            }
        }
    }
}
